### ISSUE TITLE
Sharing, and Professional Fee field is not present when editing the listing

### ISSUE THREAD

**Issue by prime-melvic** [PRIMEPH-IT/sis#223]
a.	Occurences: Always
b.	No. of affected: User that can edit a listing.
c.	Reproduction:
i.	View a listing then click the edit button in the summary of listing.
d.	Course of Action:
i.	Update the form of edit listing and add two field for sharing and professional fee together with that update of controller so it will be send to the api.
e.	Notes: 
i.	Must be add soon.

**Comment by prime-ralph** [comment]
Now editable.
