### ISSUE TITLE
Increase of size limit upload

### ISSUE THREAD

**Issue by prime-melvic** [PRIMEPH-IT/sis#226]
a.	Occurences: Rare
b.	No. of affected: All users.
c.	Reproduction:
i.	Succeed toast was displayed after uploading a medium to large size file.
d.	Course of Action:
i.	Increase or improve the file upload limit.
e.	Notes: 
i.	Status column shows nothing when uploading.

**Comment by prime-ralph** [comment]
1. Open XAMPP's php.ini and increase the ff:
upload_max_filesize
post_max_size
2. restart the server.

**Comment by prime-melvic** [comment]
changed in xampp
