### ISSUE TITLE
Breadcrumb navigation

### ISSUE THREAD

**Issue by prime-melvic** [PRIMEPH-IT/sis#227]
a.	Occurences: Always
b.	No. of affected: All users.
c.	Reproduction:
i.	Open a parent folder that have one child and put sub folder in it.
ii.	Add one more folder and view it then remove the newly added folder finally observe the breadcrumb.
d.	Course of Action:
i.	Refresh the page after the deletion to avoid the error in deletion.
e.	Notes: 
i.	Conducted via manual testing. Breadcrumb link creates a folder interface even the folder is removed.

**Comment by prime-ralph** [comment]
1. There is a provided array, $scope.levels, that stores all the levels of folders navigated through $scope.loadFolder, which is called every time a folder is clicked.
2. Using the array method pop(), the latest level is removed from $scope.levels and the folder id of the parent (one level lower) is returned to the modal-calling promise.
3. An undefined if statement is used to catch cases when the parent folder is the main folder.
4. $scope.refresh's event is triggered, loading the parent folder.
