### ISSUE TITLE
Redirect of page while in “Contacts Page”

### ISSUE THREAD

**Issue by prime-melvic** [PRIMEPH-IT/sis#228]
a.	Occurences: Present
b.	No. of affected: User with brokerage privilege.
c.	Reproduction:
i.	Go to contacts page then view a contact in the table and you can see that the button on the upper left is “Back to Home”.
ii.	Go to contacts page then share,update or add inquiry on a contact in the table and you can see that the button on the upper left is “Back to Contacts”.
d.	Course of Action:
i.	Change the url and the label of the button to make it consistent.
e.	Notes: 
i.	Same case to the inquiry module.
ii.	Conducted via manual testing.

**Comment by prime-ralph** [comment]
Solution:
1. Store previous state name on $rootScope.prevState during fire of $stateChangeStart event
2. Use $rootScope.prevState for acquiring state from which the info page was loaded
3. if $rootScope.prevState==null, use Home (occurs when button click loads page on a new tab)
